# Generated by Django 4.2.1 on 2023-05-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id',      models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',    models.CharField    (blank=True, max_length=30, null=True)),
                ('image',   models.ImageField   (blank=True, default='default/no_img.jpg', null=True, upload_to='profile_pic/')),
                ('email',   models.EmailField   (blank=True, max_length=30, null=True)),
                ('age',     models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.TextField    (blank=True, max_length=300, null=True)),
                ('phone',   models.TextField    (blank=True, max_length=15, null=True)),
                ('dob',     models.TextField    (blank=True, max_length=15, null=True)),
                ('religion',models.CharField    (choices=[('Islam', 'Islam'), ('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Judaism', 'Judaism'), ('Christianity', 'Christianity')], max_length=20)),
                ('gender',  models.CharField    (choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
            ],
        ),
    ]
